@TodoApi_2_HostAddress = https://localhost:7256

GET {{TodoApi_2_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoApi_2_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

GET {{TodoApi_2_HostAddress}}/api/todoitems/1

###


PUT {{TodoApi_2_HostAddress}}/api/todoitems/1
Content-Type: application/json

{
   "id": 1,
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{TodoApi_2_HostAddress}}/api/todoitems/1

###
